<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Authors>STÜBER SYSTEMS GmbH</Authors>
    <Company>STÜBER SYSTEMS GmbH</Company>
    <Copyright>© 2026 STÜBER SYSTEMS GmbH</Copyright>
    <Product>OpenCodeList.NET</Product>
    <Description>A .NET library for parsing, validating, building and writing OpenCodeList documents</Description>
    <RepositoryType>git</RepositoryType>
    <LangVersion>latest</LangVersion>
    <Version>0.3.0</Version>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/openpotato/opencodelist.net</RepositoryUrl>
    <PackageTags>opencodelist;codelist;codelistset</PackageTags>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Enbrea.Bcp47.Iana" Version="0.1.0" />
    <PackageReference Include="Enbrea.SemVer" Version="0.3.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
  </ItemGroup>

</Project>
