<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Authors>STÜBER SYSTEMS GmbH</Authors>
    <Company>STÜBER SYSTEMS GmbH</Company>
    <Copyright>© 2025 STÜBER SYSTEMS GmbH</Copyright>
    <Product>OpenCodeList.NET</Product>
	  <Description>A .NET library for parsing and building OpenCodeList documents</Description>
    <PackageLicenseUrl></PackageLicenseUrl>
    <RepositoryType>git</RepositoryType>
    <NeutralLanguage></NeutralLanguage>
    <LangVersion>latest</LangVersion>
    <Version>0.1.0</Version>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/openpotato/opencodelist.net</RepositoryUrl>
    <PackageTags>opencodelist;codelist;codelistset</PackageTags>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
